#!/bin/bash
export SITE_PATH=/home/ubuntu/django_projects/PROJECT_NAME/PROJECT_NAME_site
GIT_WORK_TREE=$SITE_PATH git checkout -f
chmod 666 $SITE_PATH/db.sql
source /usr/local/bin/virtualenvwrapper.sh && workon PROJECT_NAME && pip install -r $SITE_PATH/requirements.txt
sudo apache2ctl graceful
#git push redmine master
